config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show]
  resources :bookings, only: [:destroy]

  resources :offers do
    resources :bookings, only: [:new, :create, :show]
  end

  patch '/bookings/:id', to: 'bookings#accept', as: 'booking_accept'
  get '/pages/profile', to: 'pages#profile', as: 'profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :offer
  belongs_to :user
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user

  mount_uploader :photo, PhotoUploader

  @categories = ["Plomberie", "Bricolage", "Jardinage", "Electricite", "Peinture", "Demenagement", "Couture", "Decoration", "Montage meubles", "Electromenager"]
  validates :category, inclusion: { in: @categories }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # validates :title, presence: true
  # validates :availability, presence: true
  # validates :price, presence: true
  # validates :active, presence: true
  # validates :place, presence: true
  # validates :category, presence: true, inclusion: { in: @categories }
  # validates :user_id, presence: true, uniqueness: true


  include PgSearch::Model
  pg_search_scope :search_by_title,
    against: [:title],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :offers
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :phone_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :phone_number, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy, :accept]
  def show
  end

  def new
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new(booking_params)
    @booking.offer = @offer
    @booking.user = current_user
    if @booking.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
  end

  def accept
    @booking.status = true
    @booking.save
    redirect_to user_path(@booking.offer.user_id)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:adress, :date, :offer_id)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show]

@categories = ["Plomberie", "Bricolage", "Jardinage", "Electricite", "Peinture", "Demenagement", "Couture", "Decoration", "Montage meubles", "Electromenager"]

  def index
    if params[:keyword].present?
      @offers = Offer.geocoded.where("title ILIKE ?", "%#{params[:keyword]}%")
      @markers = @offers.map do |offer|
        {
          lat: offer.latitude,
          lng: offer.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { offer: offer }),
          image_url: helpers.asset_url('picto_balai.png')
        }
      end
    elsif params[:query].present?
      @offers = Offer.geocoded.where(category: params[:query])
      @markers = @offers.map do |offer|
        {
          lat: offer.latitude,
          lng: offer.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { offer: offer }),
          image_url: helpers.asset_url('picto_balai.png')
        }
      end
    else
      @offers = Offer.geocoded.all
      @markers = @offers.map do |offer|
        {
          lat: offer.latitude,
          lng: offer.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { offer: offer }),
          image_url: helpers.asset_url('picto_balai.png')
        }
      end
    end
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    if @offer.save
     redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    if @offer.update(offer_params)
      redirect_to offer_path(@offer)
    else
      render :edit
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :availability, :price, :active, :place, :category, :photo, :date, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :profile]

  def home
  end

  def profile
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def article_params
    params.require(:user).permit(:email, :encrypted_password, :reset_password_token, :username, :phone_number, :first_name, :last_name, :photo, :photo_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/destroy.js.erb
document.querySelector("[data-booking-id='<%= @booking.id %>']")
  .remove();

app/views/bookings/new.html.erb
<div class="form">
<h2>Réserver <%= @offer.title %></h2>

<%= simple_form_for [@offer, @booking] do |f| %>
  <%= f.input :adress, label: 'Votre addresse', placeholder: '23 avenue des anneaux, Saturne' %>
  <%= f.input :description, label: 'Description du service', placeholder: "Virer la ceinture d'asteroïdes de ma vue !" %>
  <%= f.submit "Reserver", class: "btn" %>
<% end %>
</div>

app/views/bookings/show.html.erb
<h2><%= @booking.offer.title %></h2>

<p><%= @booking.adress %></p>
<% if @booking.status %>
  <p>Acceptée</p>
<% else %>
  <p>En attente</p>
<% end %>
<p>Dans <%= @booking.date.day - Date.today.day if @booking.date %> jour(s)</p>

<%= link_to 'Accepter', booking_accept_path(@booking), method:'patch' %>
<%= link_to 'Supprimer', booking_path, method:'delete' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Loue Mon Conjoint</title>
    <link rel="icon" type="image/png"  href="../../assets/images/favicon-16x16.png" />
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
<!--       <p class="notice"><%= notice %></p> -->
      <!-- <p class="alert"><%= alert %></p> -->

    <!-- <%= render 'shared/flashes' %> -->
    <%= render 'shared/header' %>

    <div class="body-content">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

</body>



</html>

app/views/offers/_form.html.erb
<div class="form"=>
  <%= simple_form_for @offer do |f| %>
    <%= f.input :title, label: "Titre", placeholder: "Je tonds votre petit jardin" %>
    <%= f.input :description, as: :text, label: "Description", placeholder: "Je tonds, coupe, taille, bref je n'ai pas peur de la brousaille ..." %>
    <%= f.input :date, label: "Date" %>
    <%= f.input :category, label:"Categorie", collection: ["Plomberie", "Bricolage", "Jardinage", "Electricite", "Peinture", "Demenagement", "Couture", "Decoration", "Montage meubles", "Electromenager"] %>
    <%= f.input :address, label:"Localisation" %>
    <%= f.input :price,label: "Prix / heure"%>
    <%= f.input :active, label:"Désactiver mon annonce", as: :boolean, checked_value: false, unchecked_value: true %>
    <%= f.input :photo, label: "Télécharger une photo de vos réalisations", required: false%>
    <%= f.input :photo_cache, as: :hidden, required: false %>
    <%= f.button :submit, "Publier", class:"btn" %>
  <% end %>

</div>

app/views/offers/_info_window.html.erb
<p><strong><%= offer.title %></strong></p>
<p>Catégorie: <%= offer.category %></p>
<p><%= offer.address %></p>
<%= link_to "Plus d'infos", offer_path(offer), class:"btn-small" %>

app/views/offers/destroy.js.erb
document.querySelector("[data-offer-id='<%= @offer.id %>']")
  .remove();

app/views/offers/edit.html.erb
<%= render 'form', offer: @offer %>

app/views/offers/index.html.erb
<h3 id="title-page-offer">Toutes les annonces disponibles : <span id="category-title-orange"><%= params[:query] %></span></h3>

<div id="map" class="rounded mx-auto"
  style="width: 80vw; height: 50vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
</div>

<div class="offers-container">
  <% @offers.each do |offer| %>
    <%= link_to offer_path(offer), class:"link-card" do %>
    <div class="card-trip mb-4">
      <img src="https://cdn.pixabay.com/photo/2016/02/28/12/00/gift-1226848_960_720.jpg" />
      <div class="card-trip-infos">
        <div>
          <p><%= offer.user.username %> -- dispo le : <%= offer.date %></p>
          <h2><%= offer.title %></h2>
        </div>
        <span class="card-trip-pricing"> <%= offer.price %>€</span>
        <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> -->
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/offers/new.html.erb
<%= render 'form', offer: @offer %>

app/views/offers/show.html.erb
<div class="offer-navbar">
  <%= link_to "Retour", offers_path, class:"btn-light" %>
  <%= link_to "Réserver", new_offer_booking_path(@offer), class:"btn"  %>
</div>

<div class="offer-container">

  <div class="offer-header d-flex justify-content-between">
    <div class="offer-photo">
      <% if @offer.user.photo.present? %>
        <%= cl_image_tag @offer.user.photo, class: "offer-photo"%>
      <% else %>
        <img src="https://image.flaticon.com/icons/svg/126/126486.svg"/>
      <% end %>
    </div>

    <div class="offer-summary">
      <div class="offer-tagline d-flex justify-content-between">
        <h2><%= @offer.user.username %></h2>
        <h2><%= @offer.price %> €/h</h2>
      </div>
      <h3><%= @offer.title%></h3>
       <br>
       <h3><%= @offer.address %></h3>
      <h3>Pour le : <%= @offer.date%></h3>

    </div>
  </div>

  <div class="offer-description">
    <h3>Description : <%= @offer.description %> </h3>
  </div>

</div>

<div class="realisation-photo">
  <% if @offer.photo.present? %>
    <%= cl_image_tag @offer.photo, class: "realisation-photo" %>
  <% else %>
  <img src="https://images.pexels.com/photos/33343/building-joy-planning-plans.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260", class="realisation-photo"/>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/33343/building-joy-planning-plans.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
  <div class="container">
    <h1 id="title">SuperVoisin </h1>
    <div class="text-js">
      <p><span id="banner-typed-text"></span></p>
    </div>
    <a class="btn btn-pub-annonce" href="/offers/new">Publier une annonce</a>
  </div>
</div>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-8 col-md-8 col-lg-8">
      <form novalidate="novalidate" class="simple_form search" id="search-forme" action="/offers" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="keyword" id="search_keyword" />
          <button name="button" type="submit" class="btn btn-flat">
            <i class="fas fa-search"></i> Search
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="category-container overflow-auto">

  <%= link_to offers_path(query: "Bricolage") do %>
    <div class="cards-category" style="background-image: url( <%= image_path 'bricolage.png'%>)">
      Bricolage
    </div>
  <% end %>

  <%= link_to offers_path(query: "Couture") do %>
    <div class="cards-category" style="background-image: url( <%= image_path 'couture.png'%>)">
      Couture
    </div>
  <% end %>

  <%= link_to offers_path(query: "Decoration") do %>
    <div class="cards-category" style="background-image: url( <%= image_path 'decoration.png'%>)">
      Décoration
    </div>
  <% end %>

  <%= link_to offers_path(query: "Demenagement") do %>
    <div class="cards-category" style="background-image: url( <%= image_path 'demenagement.png'%>)">
      Déménagement
    </div>
  <% end %>

  <%= link_to offers_path(query: "Electricite") do %>
    <div class="cards-category" style="background-image: url( <%= image_path 'electricite.png'%>)">
      Electricité
    </div>
  <% end %>

  <%= link_to offers_path(query: "Electromenager") do %>
    <div class="cards-category" style="background-image: url( <%= image_path 'electromenager.png'%>)">
      Electroménager
    </div>
  <% end %>

  <%= link_to offers_path(query: "Jardinage") do %>
    <div class="cards-category" style="background-image: url( <%= image_path 'jardinage.png'%>)">
      Jardinage
    </div>
  <% end %>

  <%= link_to offers_path(query: "Peinture") do %>
    <div class="cards-category" style="background-image: url( <%= image_path 'peinture.png'%>)">
      Peinture
    </div>
  <% end %>

  <%= link_to offers_path(query: "Petits-travaux") do %>
    <div class="cards-category" style="background-image: url( <%= image_path 'petits-travaux.png'%>)">
      Petits travaux
    </div>
  <% end %>

</div>

app/views/pages/profile.html.erb
<div class="form">
  <span class="d-flex">
    <% if current_user.photo.present? %>
    <%= cl_image_tag current_user.photo, class: "avatar"%>
    <% else %>
    <%= image_tag "https://cdn.pixabay.com/photo/2017/02/25/22/04/user-icon-2098873_1280.png", class: "avatar" %>
    <% end %>
    <h2> Bonjour <%= current_user.first_name %> <%= current_user.last_name %></h2>
  </span>
  <p>Surnom: <%= current_user.username %> </p>
  <p>Email: <%= current_user.email %></p>
  <p>Phone number: <%= current_user.phone_number %></p>
  <%= link_to "Modifer", edit_user_registration_path, class: 'btn' %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container fixed-bottom row">
    <%= link_to "/", class: "card col" do %>
      <i class="fas fa-search"></i>
      <h5 class="card-title">Recherche</h5>
    <% end %>

    <%= link_to new_offer_path, class: "card col" do %>
      <i class="far fa-plus-square"></i>
      <h5 class="card-title">Publier</h5>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to user_path(current_user), class: "card col" do %>
      <i class="far fa-calendar"></i>
      <h5 class="card-title">Tableau de bord</h5>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "card col" do %>
      <i class="far fa-user"></i>
      <h5 class="card-title">Connexion</h5>
    <% end %>
    <% end %>
 </div>

app/views/shared/_header.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "LMC-logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <% if user_signed_in? %>
    <span class="navbar-toggler">
      <% if current_user.photo.present? %>
      <%= cl_image_tag current_user.photo, class: "avatar", 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
      <%= image_tag "https://cdn.pixabay.com/photo/2017/02/25/22/04/user-icon-2098873_1280.png", class: "avatar" , 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
    <% else %>
      <span class="navbar-toggler-icon"></span>
    <% end %>
    </span>
  </button>


 <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Accueil", "/", class: "dropdown-item" %>
        </li>
        <li>
          <%= link_to "Profil", profile_path, method: :get, class: "dropdown-item"%>
        </li>
        <li>
          <%= link_to "Déconnexion", destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: :delete, class: "dropdown-item"%>

        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="banner profil-banner mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.pixabay.com/photo/2016/02/19/11/32/tools-1209764_960_720.jpg);">
  <div class="container">
    <h1>Bienvenue <strong><%= @user.username %></strong>!</h1>
  </div>
</div>

<div class="container">
  <div class="tab d-flex justify-content-between">
    <button class="tablinks active">Annonces</button>
    <button class="tablinks">Missions</button>
    <button class="tablinks">Reservations</button>
  </div>

  <div id="Annonces" class="tabcontent">
    <% if(@user.offers != []) %>
      <div class="row justify-content-center">
        <% @user.offers.each do |offer| %>
          <div class="card text-center m-3" style="width: 18rem; margin-bottom: 7px; border-radius: 5px;" data-offer-id="<%= offer.id %>">
          <%= cl_image_tag offer.photo, class: "card-img-top"%>
            <div class="card-body" style="padding: 7px;">
              <h5 class="card-title"><%= offer.title %></h5>
              <p class="card-text"><%= offer.description %></p>
              <p class="card-text">Pour le : <%= offer.date %></p>
              <div class="card-link-annonce d-flex justify-content-around">
                <p><%= link_to "Mettre à jour", edit_offer_path(offer.id), class:"btn" %></p>
                <p style="font-size: 30px; color: #f38c73;">
                  <%= link_to offer_path(offer), method: :delete, remote: true do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>Vous n'avez pas d'offre en cours !</p>
    <% end %>
    <%= link_to "Publier une nouvelle offre", new_offer_path, class:"btn mt-3" %>
  </div>

  <div id="Missions" class="tabcontent not-displayed rounded">
    <% if(@user.offers != []) %>
      <% @user.offers.each do |offer| %>
        <% offer.bookings.each do |booking| %>
          <div class="card text-center mb-4" data-booking-id="<%= booking.id %>">
            <div class="card-header">
              <%= offer.category %>
            </div>
            <div class="card-body">
              <h5 class="card-title">Mission</h5>
              <p class="card-text">
                  <ul>
                    <li><%= booking.description %></li>
                    <li><%= booking.adress %></li>
                    <li>Le : <%= offer.date %></li>
                  </ul>
              </p>

              <% if booking.status %>
                <p>mission acceptée !</p>
              <% else %>
                <%= link_to "Accepter", booking_accept_path(booking), method:"patch", class:"btn" %>
              <% end %>
              <%= link_to booking_path(booking), method: :delete, remote: true do %>
                <button type="button" class="btn">Refuser</button>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              2 days ago
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p>Vous n'avez pas d'offre en cours !</p>
      <%= link_to "Publier une nouvelle offre", new_offer_path, class:"btn" %>
    <% end %>
  </div>

  <div id="Reservations" class="tabcontent not-displayed">
    <% if(@user.bookings != []) %>
      <% @user.bookings.each do |booking| %>
        <div class="card-product rounded">
          <%= cl_image_tag booking.offer.photo%>
          <div class="card-product-infos">
            <h2><%= booking.description %></h2>
            <p><%= booking.adress %></p>
            <p><%= booking.offer.date %></p>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>Vous n'avez pas de réservation !</p>
    <% end %>
    <%= link_to "Trouver un conjoint", root_path, class:"btn" %>
  </div>
</div>